CREATE TABLE IF NOT EXISTS BadgerUser (
	id INTEGER PRIMARY KEY,
	username TEXT NOT NULL UNIQUE,
	passwd TEXT NOT NULL,
	salt TEXT NOT NULL,
	xcsid TEXT NOT NULL,
	wiscUsername TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS BadgerMessage (
	id INTEGER PRIMARY KEY UNIQUE,
	poster TEXT NOT NULL,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	chatroom TEXT NOT NULL,
	created TIMESTAMP NOT NULL
);